import { useState } from 'react';
import '../styles/FAQSection.css';


const FAQSection = () => {
  const [openQuestion, setOpenQuestion] = useState(null);

  const faqData = [
    {
      question: "Who owns the content produced using JustDone.ai?",
      answer: "You retain full ownership of the content you create using JustDone.ai. The platform is designed to assist and enhance your writing process, but the intellectual property rights of the generated content belong to you."
    },
    {
      question: "Can the output generated by JustDone.ai be plagiarized?",
      answer: "JustDone.ai generates original content based on your inputs. However, it's always a good practice to review and verify the output to ensure it meets your needs and standards."
    },
    {
      question: "Who can benefit from using JustDone.ai?",
      answer: "JustDone.ai can benefit a wide range of users, including content creators, marketers, writers, and businesses looking to streamline their content creation process."
    },
    {
      question: "How does JustDone.ai ensure data privacy and protection?",
      answer: "JustDone.ai takes data privacy seriously. We implement industry-standard security measures to protect your data and ensure that your information remains confidential."
    },
    {
      question: "Is JustDone.ai capable of handling large-scale content generation projects?",
      answer: "Yes, JustDone.ai is designed to handle both small and large-scale content generation projects efficiently."
    },
    {
      question: "How accurate is the content generated by JustDone.ai?",
      answer: "JustDone.ai strives for high accuracy, but as with any AI-generated content, it's recommended to review and fact-check the output for your specific use case."
    },
    {
      question: "Can I use JustDone.ai for different types of content, such as blog posts, social media captions, or email newsletters?",
      answer: "Yes, JustDone.ai is versatile and can be used to generate various types of content, including blog posts, social media captions, and email newsletters."
    },
    {
      question: "Can JustDone.ai help me optimize my content for search engines?",
      answer: "JustDone.ai can assist in creating SEO-friendly content. However, for best results, combine its output with your SEO strategy and expertise."
    },
    {
      question: "Does JustDone.ai provide customer support in case I need assistance?",
      answer: "Yes, JustDone.ai offers customer support to help you with any questions or issues you may encounter while using the platform."
    }
  ];

  const toggleQuestion = (index) => {
    setOpenQuestion(openQuestion === index ? null : index);
  };

  return (
    <div className="faq-section">
      <div className="faq-header">
        <h2>Ready for a game-changer?</h2>
        <p>Create content faster, engage audience better, spend less time.</p>
        <button className="try-chartrun-btn">
          <span className="btn-icon">⚡</span>
          Try ChartRun
        </button>
      </div>
      <div className="faq-container">
        <h3>Frequently Asked Questions</h3>
        <div className="faq-list">
          {faqData.map((faq, index) => (
            <div key={index} className="faq-item">
              <div className="faq-question" onClick={() => toggleQuestion(index)}>
                <span className={`arrow ${openQuestion === index ? 'open' : ''}`}>▼</span>
                <span>{faq.question}</span>
              </div>
              {openQuestion === index && <div className="faq-answer">{faq.answer}</div>}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default FAQSection;